---
- name: Install NGINX | Install EPEL repository for NGINX
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
  ignore_errors: true

- name: Install NGINX
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: restart-nginx
  ignore_errors: true

- name: Create NGINX config
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: restart-nginx
  ignore_errors: true
